# The following codes are auto generated by ChatGPT. It is a snake game. :)
# 以下代码是由ChatGPT自动生成的。实现了一个贪吃蛇小游戏。 
# 不死版
import pygame
import random

# 定义颜色
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
RED = (255, 0, 0)

# 设置窗口大小
WIDTH = 600
HEIGHT = 400

# 设置贪吃蛇的大小和速度
BLOCK_SIZE = 10
SPEED = 15

class Snake:
    def __init__(self):
        self.length = 1
        self.positions = [(WIDTH / 2, HEIGHT / 2)]
        self.direction = random.choice([UP, DOWN, LEFT, RIGHT])
        self.color = GREEN
    
    def get_head_position(self):
        return self.positions[0]
    
    def turn(self, point):
        if self.length > 1 and (point[0]*-1,point[1]*-1) == self.direction:
            return
        else:
            self.direction = point
    
    def move(self):
        cur = self.get_head_position()
        x, y = self.direction
        new = ((cur[0] + (x*BLOCK_SIZE)), (cur[1] + (y*BLOCK_SIZE)))
        if new in self.positions[2:]:
            raise Exception
        else:
            self.positions.insert(0, new)
            if len(self.positions) > self.length:
                self.positions.pop()
                
    def reset(self):
        self.length = 1
        self.positions = [(WIDTH / 2, HEIGHT / 2)]
        self.direction = random.choice([UP, DOWN, LEFT, RIGHT])
        
    def draw(self, surface):
        for p in self.positions:
            r = pygame.Rect((p[0], p[1]), (BLOCK_SIZE, BLOCK_SIZE))
            pygame.draw.rect(surface, self.color, r)
            pygame.draw.rect(surface, BLACK, r, 1)

class Food:
    def __init__(self):
        x = random.randrange(0, WIDTH, BLOCK_SIZE)
        y = random.randrange(0, HEIGHT, BLOCK_SIZE)
        self.position = (x, y)
        self.color = RED
        
    def draw(self, surface):
        r = pygame.Rect((self.position[0], self.position[1]), (BLOCK_SIZE, BLOCK_SIZE))
        pygame.draw.rect(surface, self.color, r)
        pygame.draw.rect(surface, BLACK, r, 1)

# 定义方向常量
UP = (0, -1)
DOWN = (0, 1)
LEFT = (-1, 0)
RIGHT = (1, 0)

def main():
    pygame.init()
    pygame.display.set_caption("贪吃蛇小游戏")

    # 创建窗口
    screen = pygame.display.set_mode((WIDTH, HEIGHT))

    clock = pygame.time.Clock()

    # 创建贪吃蛇和食物对象
    snake = Snake()
    food = Food()

    while True:
        # 监听退出事件
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
               
        # 监听键盘事件，控制贪吃蛇的移动方向
        keys = pygame.key.get_pressed()
        for key in keys:
            if keys[pygame.K_LEFT]:
                snake.turn(LEFT)
            elif keys[pygame.K_RIGHT]:
                snake.turn(RIGHT)
            elif keys[pygame.K_UP]:
                snake.turn(UP)
            elif keys[pygame.K_DOWN]:
                snake.turn(DOWN)

        # 移动贪吃蛇和检查是否吃到食物
        snake.move()
        if snake.get_head_position() == food.position:
            snake.length += 1
            food = Food()

        # 检查游戏是否结束
        try:
            if any((HEAD == snake.get_head_position()) for HEAD in snake.positions[1:]):
                snake.reset()
        except Exception:
            snake.reset()

        # 绘制游戏画面
        screen.fill(WHITE)
        snake.draw(screen)
        food.draw(screen)
        pygame.display.update()

        # 控制游戏速度
        clock.tick(SPEED)

if __name__ == "__main__":
    main()
